name = "cloudflare-docker-proxy"
compatibility_date = "2025-03-12"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "ducust.site"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[env.production]
name = "cloudflare-docker-proxy"
routes = [
  { pattern = "docker.ducust.site", custom_domain = true },
  { pattern = "quay.ducust.site", custom_domain = true },
  { pattern = "gcr.ducust.site", custom_domain = true },
  { pattern = "k8s-gcr.ducust.site", custom_domain = true },
  { pattern = "k8s.ducust.site", custom_domain = true },
  { pattern = "ghcr.ducust.site", custom_domain = true },
  { pattern = "cloudsmith.ducust.site", custom_domain = true },
]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.ducust.site", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
